name: PHP Validate
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test build PHP 7.4
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
        env:
          PHP_VERSION: 7.4

      - name: Test build PHP 8
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
        env:
          PHP_VERSION: 8
